# This is a configuration file for the bacon tool
#
# Bacon repository: https://github.com/Canop/bacon
# Complete help on configuration: https://dystroy.org/bacon/config/
# You can also check bacon's own bacon.toml file
#  as an example: https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "nextest"

[jobs.coverage]
command = ["cargo", "tarpaulin", "--verbose", "--color", "always", "--out", "lcov", "--out", "html", "--include-tests", "--ignore-panics", "--count",
           "--output-dir", "target-coverage", "--skip-clean", "--engine", "llvm", "--exclude-files", "target/*"]
env.CARGO_TARGET_DIR = "target-coverage"
need_stdout = false
on_change_strategy = "wait_then_restart"
background = true

[jobs.nextest]
# --stress-count=N: repeat every test a few times to find flaky ones
command = ["cargo", "nextest", "run", "--color", "always", "--profile", "default"]
need_stdout = true
analyzer = "nextest"
on_change_strategy = "wait_then_restart"
background = true

[jobs.fuzz]
command = ["cargo", "--color", "always", "fuzz", "run", "write-read-large-files"]
need_stdout = true
on_change_strategy = "wait_then_restart"
background = false
