[toolchain]
channel = "nightly-2025-09-08"
components = ["rustfmt", "clippy", "cargo", "rustc", "llvm-tools-preview"]
targets = ["x86_64-pc-windows-msvc", "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
profile = "minimal"
