[toolchain]
channel = "nightly"
components = ["rustfmt", "clippy", "cargo", "rustc", "llvm-tools-preview"]
targets = ["wasm32-wasip1", "wasm32-wasip1-threads", "x86_64-pc-windows-msvc", "aarch64-unknown-linux-gnu"]
profile = "minimal"
