[package]
name = "dogbox_blob_layer"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
serde = {version = "1.0", features = [ "derive" ]}
sha3 = "0.10"
hex = "0.4"
async-trait = "0.1"
tokio = { version = "1.3", features = ["full"] }
tokio-macros = "2.2"
