[package]
name = "dogbox_tree_editor"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
dogbox_tree = { path ="../dogbox_tree" }
futures-core = "0.3"
relative-path = "1.9"
tokio = { version = "1.3.0", features = ["full"] }
futures = "0.3"
async-stream = "0.3"
bytes = "1.0"
