# https://nexte.st/docs/configuration/

[profile.default]
slow-timeout = { period = "3s", terminate-after = 3 }
fail-fast = true
retries = 2

[profile.ci]
# Do not cancel the test run on the first failure.
fail-fast = false
