# https://nexte.st/docs/configuration/

[profile.default]
slow-timeout = { period = "5s", terminate-after = 4 }
fail-fast = false
retries = 1

[profile.ci]
# Do not cancel the test run on the first failure.
fail-fast = false
